//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikli()
        {
            this.Stavka_kosarice = new HashSet<Stavka_kosarice>();
        }
    
        public int Id_Artikla { get; set; }
        public string NazivArtikla { get; set; }
        public Nullable<decimal> CijenaArtikla { get; set; }
        public Nullable<int> ProdavacID { get; set; }
    
        public virtual Prodoavac Prodoavac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_kosarice> Stavka_kosarice { get; set; }
    }
}
