//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        public int Id_narudzbe { get; set; }
        public string Broj_narudzbe { get; set; }
        public Nullable<int> Id_kosarice { get; set; }
        public Nullable<int> ProdavacID { get; set; }
    
        public virtual Prodoavac Prodoavac { get; set; }
        public virtual Stavka_kosarice Stavka_kosarice { get; set; }
    }
}
