//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodoavac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prodoavac()
        {
            this.Artiklis = new HashSet<Artikli>();
            this.Narudzbas = new HashSet<Narudzba>();
        }
    
        public int ProdavacID { get; set; }
        public string NazivFirme { get; set; }
        public Nullable<int> OIB { get; set; }
        public string Vlasnik { get; set; }
        public string Telefon { get; set; }
        public string email { get; set; }
        public string KorisnickoIme { get; set; }
        public string sifra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artikli> Artiklis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> Narudzbas { get; set; }
    }
}
