//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_kosarice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stavka_kosarice()
        {
            this.Kosaricas = new HashSet<Kosarica>();
            this.Narudzbas = new HashSet<Narudzba>();
        }
    
        public int Id_kosarice { get; set; }
        public Nullable<double> Suma { get; set; }
        public Nullable<int> Kollicina { get; set; }
        public Nullable<int> Id_Artikla { get; set; }
        public string NazivArtikla { get; set; }
        public Nullable<decimal> CijenaArtikla { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kosarica> Kosaricas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> Narudzbas { get; set; }
    }
}
